[package]
name = "battista"
version = "0.1.0"
authors = ["Sebastian Wicki <gandro@gmx.net>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
battista-ftp-parser = { path = "parser" }

[workspace]
